Add NativeCapture
BabylonJS/BabylonReactNative pull request #156
Opened 2021-02-10 18:58 UTC by ryantrem

The `NativeCapture` plugin was recently added to BabylonNative. This change pulls it into BabylonReactNative and adds a TypeScript wrapper. It also logs a warning if it is used since:
1. We expect it may change.
2. Ultimately it should be exposed through a Babylon.js API.

FYI @bonnyMahajan10

2021-02-10 20:11 UTC, chrisfromwork commented
>     <ProjectReference Include="$(BabylonReactNativeDir)\submodules\BabylonNative\Build_uwp_x64\Core\Graphics\Graphics.vcxproj">

NativeCapture needs added to these different platform specific library references. This should generate linker errors with pr ci

---
Refers to: Modules/@babylonjs/react-native-windows/windows/BabylonReactNative/BabylonReactNative.vcxproj:205 in a5334b1. [](commit_id = a5334b11407750186578eca68dae843b003b5479, deletion_comment = False)

2021-02-10 20:11 UTC, chrisfromwork requested changes
NativeCapture needs added to these different platform specific library references in BabylonReactNative.vcxproj. This should theoretically generate linker errors with pr ci

2021-02-11 00:04 UTC, Alex-MSFT approved these changes

2021-02-11 00:07 UTC, chrisfromwork commented on Modules/@babylonjs/react-native/NativeCapture.ts
> +declare class NativeCapture {
long term are we planning to have this defined somewhere in Babylon.js?

2021-02-11 00:07 UTC, chrisfromwork approved these changes

2021-02-11 00:12 UTC, merged